Added LSM configuration
yast/yast-installation pull request #1006
Opened 2021-12-15 12:41 UTC by teclator

2021-12-23 13:31 UTC, dgdavid commented on src/lib/installation/clients/security_finish.rb
>          # Write down selinux configuration
```suggestion
        # Write down the Linux Security Module configuration
```

2021-12-23 13:31 UTC, dgdavid commented on src/lib/installation/clients/security_proposal.rb
> +            "Linux Security Module: Activate SELinux in '%s' mode"
Not sure if we can use the `lsm_config.selected.label` here. Or even if it worth.

2021-12-23 13:31 UTC, dgdavid commented on src/lib/installation/clients/security_proposal.rb
> +        when :none
I miss the `else` here. I mean, for :none or **nil** (_...lsm\_config.selected_**&**_.id_) it should be the same proposal, shouldn't it?

2021-12-23 13:31 UTC, dgdavid commented on src/lib/installation/widgets/lsm.rb
> +        # TRANSLATORS: SELinux Mode just SELinux is already content of frame.
Sorry, I did not understand that comment

2021-12-23 13:31 UTC, dgdavid commented on src/lib/installation/widgets/lsm.rb
> +          Yast::HTML.List(available_modules.map(&:label))
Note: I guess we are going to improve the help text in subsequent PR

2021-12-23 13:31 UTC, dgdavid commented on test/lib/clients/security_proposal_test.rb
> +      it "contains in proposal LSM configuration" do
We're testing the proposal, let's simplify the test description (which comes from the previous changes, I know)

```suggestion
      it "contains the LSM configuration" do
```

2021-12-23 13:32 UTC, dgdavid commented
@teclator 

It'd be nice to have some screenshots in the PR description. I can help with it if needed.

Thanks!

2021-12-24 10:47 UTC, dgdavid requested changes
Do not forget bump version, update changelog and update requirements/dependencies if needed. Thank you!


:santa: :christmas_tree:

2021-12-27 07:33 UTC, teclator commented on src/lib/installation/clients/security_proposal.rb
> +        when :none
Not really, in case it is `nill` nothing will shown which means **AppArmor** will be enabled by default, therefore there is no `lsm` option passed to the kernel during boot.

2021-12-27 07:35 UTC, teclator commented on src/lib/installation/widgets/lsm.rb
> +        # TRANSLATORS: SELinux Mode just SELinux is already content of frame.
It is a leftover, which I have not adapted :)

2021-12-27 07:36 UTC, teclator commented on src/lib/installation/widgets/lsm.rb
> +          Yast::HTML.List(available_modules.map(&:label))
Yep, but leave it to be addressed by a separate card by now

2021-12-27 11:23 UTC, dgdavid commented on src/lib/installation/clients/security_proposal.rb
> +                   "Linux Security Module: Activate %s in '%s' mode"
Should we add the `# TRANSLATORS:` comment for clarifying for what the text is? What is more, should we use the `%{module}` and `%{mode}` instead of `%s`?

Just asking.

2021-12-27 11:23 UTC, dgdavid commented on src/lib/installation/dialogs/security.rb
> +                HStretch()
:+1:

2021-12-27 11:24 UTC, dgdavid commented on src/lib/installation/dialogs/security.rb
> +                HStretch()
:+1:

2021-12-27 11:24 UTC, dgdavid commented on src/lib/installation/widgets/lsm.rb
> +require "yast"
NP: add the copyright header.

2021-12-27 11:25 UTC, dgdavid commented on src/lib/installation/widgets/lsm.rb
> +    class LSM < CWM::CustomWidget
NP: let's document the widget a bit. Something like

```suggestion
    # Widget for managing the LSM configuration during installation
    class LSM < CWM::CustomWidget
```

or better.

2021-12-27 17:00 UTC, jreidinger commented on .rubocop.yml
> +  TargetRubyVersion: 2.3
Is it really needed?? Our supported version is 2.5. At least please add comment why it is needed

2021-12-27 17:01 UTC, teclator commented on .rubocop.yml
> +  TargetRubyVersion: 2.3
With the rubocop version inherited this is the bigger one I was able to select.

2021-12-27 17:01 UTC, teclator commented on .rubocop.yml
> +  TargetRubyVersion: 2.3
Error: Unknown Ruby version 2.5 found in `TargetRubyVersion` parameter (in /home/suse/SUSE/Development/yast-meta/installation/.rubocop.yml).
Known versions: 1.9, 2.0, 2.1, 2.2, 2.3

2021-12-27 17:02 UTC, dgdavid approved these changes
LGTM

2021-12-27 17:02 UTC, dgdavid commented on src/lib/installation/clients/security_proposal.rb
> +                   "Linux Security Module: Activate %{module}s in '%{mode}' mode"
NP: is that `s` a leftover?

2021-12-27 17:02 UTC, jreidinger commented on src/lib/installation/clients/security_proposal.rb
> +                   "Linux Security Module: Activate %{module}s in '%{mode}' mode"
not sure about english, but should not be it "in the '%{mode}' mode" ?

2021-12-27 17:02 UTC, teclator commented on .rubocop.yml
> +  TargetRubyVersion: 2.3
Well, we should move to /usr/share/YaST2/data/devtools/data/rubocop-0.71.0_yast_style.yml ASAP

2021-12-27 17:03 UTC, jreidinger commented on src/lib/installation/widgets/lsm.rb
> +      # It refresh the widget content dinamically when the selection of the LSM is modified
dynamically

2021-12-27 17:03 UTC, teclator commented on src/lib/installation/clients/security_proposal.rb
> +                   "Linux Security Module: Activate %{module}s in '%{mode}' mode"
Fixed

2021-12-27 17:08 UTC, teclator commented on src/lib/installation/clients/security_proposal.rb
> +                   "Linux Security Module: Activate %{module}s in '%{mode}' mode"
I checked some official documentation when decided which label to use and there it omitted the article, but is something probably for @mvidner

2021-12-27 17:13 UTC, jreidinger commented on .rubocop.yml
> +  TargetRubyVersion: 2.3
ah, it using old rubocop. Then agreed and keep it as it is

2021-12-27 17:13 UTC, jreidinger approved these changes

2021-12-27 17:18 UTC, merged