ignore cpu_mitigations for bootloaders which do not support cpu mitig…
yast/yast-installation pull request #1093
Opened 2023-07-04 15:56 UTC by schubi2

…ations e.g. none/systemd-boot

## Problem

systemd-boot bootloader currently does not support cpu mitigation. So no proposal should be shown for this 
setting like "none" bootloader is already doing it. So this is more a generic solution for it.

- https://github.com/yast/yast-bootloader/pull/686

## Solution

Checking if the corresponding bootloader has a cpu_mitigations call.

## Testing
- Tested manually

2023-08-18 08:50 UTC, jreidinger commented
change looks good, just please bump version and add changelog entry. Thanks

2023-09-05 07:42 UTC, jreidinger commented
OK, one more change is required at https://github.com/yast/yast-installation/blob/master/src/lib/installation/dialogs/security.rb#L124 which use wrong name

2023-09-05 11:31 UTC, mvidner requested changes

2023-09-05 12:11 UTC, mvidner approved these changes

2023-09-05 12:15 UTC, merged