Security proposal
yast/yast-installation pull request #906
Opened 2021-01-28 17:36 UTC by jreidinger

2021-02-23 08:36 UTC, dgdavid commented on src/lib/installation/security_settings.rb
> +      require "y2security/selinux"
Why not put this require at the very beginning, immediately after `require 'yast'` one?

2021-02-23 10:13 UTC, jreidinger commented on src/lib/installation/security_settings.rb
> +      require "y2security/selinux"
I do lazy loading for now to not care about dependencies for tests. I will need to take care about it now.

2021-02-23 14:24 UTC, lkocman commented
Confirming that TW and Leap want to have permissive mode by default. Enforcing with imperfect policies could lead to developing habit of turning selinux off and we want to avoid that.

2021-02-25 01:00 UTC, dgdavid requested changes
In general looks good to me. Just minor things plus two suggestions:

* to split a bit the SecurityFinish#write method and 
* to rename the SelinuxPolicy widget to SelinuxMode

However, the reason I'm putting the PR in "requests changes" mode is because there is a commented test unit and it is not clear to me if it is intentional or a left over. Could you please have a look?

Thanks!

2021-02-25 01:00 UTC, dgdavid commented on src/lib/installation/clients/security_finish.rb
> +        end
NP: I'd move this to its own method, `write_firewall_and_ssh_settings` or similar with its own guard clause `return if Yast::Mode.Update`

2021-02-25 01:00 UTC, dgdavid commented on src/lib/installation/clients/security_finish.rb
> +        end
NP: and I'd move this to `write_polkit_settings` too

2021-02-25 01:00 UTC, dgdavid commented on src/lib/installation/security_settings.rb
> +      require "y2security/selinux"
Still thinking that this `require` could be moved to the top

2021-02-25 01:00 UTC, dgdavid commented on test/lib/clients/security_finish_test.rb
> +  xdescribe "#write" do
Is this a left over?

2021-02-25 01:00 UTC, dgdavid commented on src/lib/installation/widgets/selinux_policy.rb
> +    class SelinuxPolicy < CWM::ComboBox
The widget actually manage the SELinux _mode_, not the _policy_. So, I'd rename it to be more accurate.

2021-02-25 01:00 UTC, dgdavid commented on src/lib/installation/widgets/selinux_policy.rb
> +        # TRANSLATORS: SELinu Mode just SELinux is already content of frame.
NP: SELinu**x**

2021-02-25 01:00 UTC, dgdavid commented on package/yast2-installation.changes
> +  and selinux policy (jsc#SLE-17307)
NP: selinux mode

2021-02-25 09:29 UTC, dgdavid commented on package/yast2-installation.changes
> +  mitigation, policy kit default priviledges (jsc#SLE-15840)
Typo: privileges, although in every place appears as _priviledges_

2021-02-25 12:35 UTC, dgdavid requested changes

2021-02-25 12:35 UTC, dgdavid commented on src/lib/installation/clients/security_finish.rb
> +      def write_polkit
If I'm not wrong, this method is not being called.

2021-02-25 12:35 UTC, dgdavid commented on test/lib/clients/security_finish_test.rb
> +  describe "#write" do
Looks like we are not testing polkit related operations. In fact, I think that right now the new `write_polkit` private method is not being called.

2021-02-25 16:09 UTC, dgdavid approved these changes
Looks good, thanks!

2021-02-25 16:13 UTC, merged

2021-02-25 16:34 UTC, dgdavid commented
Tested manually in SLES-15-SP3

| Summary | Security client |
|-|-|
| ![Screenshot_sle15sp3-2_2021-02-25_16:30:27](https://user-images.githubusercontent.com/1691872/109184394-de125b00-7786-11eb-97f8-329a940e9541.png) | ![Screenshot_sle15sp3-2_2021-02-25_16:30:38](https://user-images.githubusercontent.com/1691872/109184461-ef5b6780-7786-11eb-8459-ee22be7562ae.png) |